runtime: nodejs22

# Instance class
instance_class: F1

# Environment variables
env_variables:
  NODE_ENV: production
  NPM_CONFIG_PRODUCTION: false
  REACT_APP_BASE_URL: https://devops-ia-backend-226162055882.asia-south1.run.app
# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Health check configuration
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Static file handlers (optional, since Express handles this)
handlers:
- url: /static
  static_dir: build/static
  secure: always
  
- url: /.*
  script: auto
  secure: always