steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci', '--production=false']
    env:
      - 'NPM_CONFIG_CACHE=/tmp/.npm'

  # Build React app
  - name: 'gcr.io/cloud-builders/npm'
    env:
      - 'REACT_APP_BASE_URL=${_BACKEND_URL}'
      - 'NODE_ENV=production'
      - 'CI=true'
      - 'NPM_CONFIG_CACHE=/tmp/.npm'
    args: ['run', 'build']

  # Verify build directory exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |
        echo "Checking build directory..."
        ls -la build/ || echo "Build directory not found!"
        echo "Checking build/static..."
        ls -la build/static/ || echo "Static directory not found!"

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'app'
      - 'deploy'
      - '--quiet'
      - '--promote'
      - '--stop-previous-version'

# Default substitutions
substitutions:
  _BACKEND_URL: 'https://devops-ia-backend-226162055882.asia-south1.run.app'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: 1800s
