steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci', '--production=false']  # Use 'ci' for faster, reliable builds
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    # Inject the backend URL as a build-time environment variable.
    # This requires you to set a `_BACKEND_URL` substitution variable in your Cloud Build trigger.
    env:
      - 'REACT_APP_BASE_URL=${_BACKEND_URL}'
      - 'NODE_ENV=production'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet', '--stop-previous-version']  # Deploy to App Engine and stop previous version

timeout: '900s'  # Optional: set a timeout for the build

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
