steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  # Build React app
  - name: 'gcr.io/cloud-builders/npm'
    env:
      - 'REACT_APP_BASE_URL=${_BACKEND_URL}'
      - 'NODE_ENV=production'
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

substitutions:
  _BACKEND_URL: 'https://devops-ia-backend-226162055882.asia-south1.run.app'

timeout: 1200s
