steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Build React app
  - name: 'gcr.io/cloud-builders/npm'
    env:
      - 'REACT_APP_BASE_URL=https://devops-ia-backend-226162055882.asia-south1.run.app'
      - 'NODE_ENV=production'
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet', '--stop-previous-version']

  - options:
    logging: CLOUD_LOGGING_ONLY

timeout: 1200s